export const languages = [
  { label: 'JavaScript', value: 'javascript' },
  { label: 'Python', value: 'python' },
  { label: 'Java', value: 'java' },
  { label: 'C++', value: 'cpp' },
  { label: 'Ruby', value: 'ruby' },
  { label: 'C#', value: 'csharp' },
  { label: 'PHP', value: 'php' },
  { label: 'Swift', value: 'swift' },
  { label: 'Kotlin', value: 'kotlin' },
  { label: 'Go', value: 'go' },
  { label: 'TypeScript', value: 'typescript' },
  { label: 'Rust', value: 'rust' },
  { label: 'Dart', value: 'dart' },
  { label: 'Scala', value: 'scala' },
  { label: 'Perl', value: 'perl' },
  { label: 'Haskell', value: 'haskell' },
  { label: 'R', value: 'r' },
  { label: 'Lua', value: 'lua' },
  { label: 'Matlab', value: 'matlab' },
  { label: 'SQL', value: 'sql' },
  { label: 'HTML', value: 'html' },
  { label: 'CSS', value: 'css' },
  { label: 'Assembly', value: 'assembly' },
  { label: 'Objective-C', value: 'objc' },
  { label: 'Groovy', value: 'groovy' },
  { label: 'Elixir', value: 'elixir' },
  { label: 'Django', value: 'django' },
  { label: 'Vue.js', value: 'vuejs' },
  { label: 'React', value: 'react' },
  { label: 'Angular', value: 'angular' },
]
export const labels = [
  { label: 'good first issue', value: 'good-first-issue' },
  { label: 'help wanted', value: 'help-wanted' },
  { label: 'documentation', value: 'documentation' },
  { label: 'bug', value: 'bug' },
  { label: 'enhancement', value: 'enhancement' },
  { label: 'invalid', value: 'invalid' },
  { label: 'question', value: 'question' },
  { label: 'wontfix', value: 'wontfix' },
  { label: 'duplicate', value: 'duplicate' },
  { label: 'feature request', value: 'feature-request' },
  { label: 'critical', value: 'critical' },
  { label: 'in progress', value: 'in-progress' },
  { label: 'high priority', value: 'high-priority' },
  { label: 'low priority', value: 'low-priority' },
  { label: 'awaiting review', value: 'awaiting-review' },
]
